services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: coffeebackend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www
      - ./backend/storage:/var/www/storage
    command: sh -c "composer install && php artisan migrate && composer run dev"

  frontend:
    build:
      context: ./frontend
    container_name: coffeefrontend
    ports:
      - 3100:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend


